### ISSUE TITLE
Update fetch teacher sql for moodle 2.7

### ISSUE THREAD

**Issue by bmbrands** [marxjohnson/moodle-block_messageteacher#14]
On Moodle 2.7.1 with full debugging on the user_picture throws a notice.

You need to update your sql to include additional name fields in the user object.
changing line 67 to 

       $select = 'SELECT DISTINCT u.id, u.firstname, u.lastname, u.firstnamephonetic, u.lastnamephonetic, u.middlename, u.alternatename, u.picture, u.imagealt, u.email ';

should fix it.

**Comment by marxjohnson** [comment]
I applied this fix some time ago, so closing.
