### ISSUE TITLE
Block Disappears

### ISSUE THREAD

**Issue by nonstopCrunchy** [marxjohnson/moodle-block_messageteacher#16]
Block disappears whenever editing is turned off in Moodle 2.7
I have
- Configured the plugin and assigned teachers and managers as visible
- Assigned roles for the course
- Configured the plugin to show on all pages
- Added the block as a different admin user
- Added other blocks to the same page in the same manner and they stay there

**Comment by marxjohnson** [comment]
Please try this with the latest version of the block (2.5). If the problem still occurs, please open a new issue.
