### ISSUE TITLE
From address shows Noreply

### ISSUE THREAD

**Issue by joejwhite** [marxjohnson/moodle-block_messageteacher#18]
Hi,
Is it possible to have the email sent to the teacher of a course include the email address of the student so that the teacher can respond directly to the email?
Currently the email is coming from noreply and the teacher must log in to the course to respond.
Thanks,
Joe

**Comment by marxjohnson** [comment]
This block just uses Moodle's internal messaging system, so I'm afraid that it can't change the addresses used in email notifications.  There may be other settings in Moodle to change this.
