### ISSUE TITLE
Issues with Moodle 2.9.3

### ISSUE THREAD

**Issue by demsley** [marxjohnson/moodle-block_messageteacher#20]
I have added the Message My Teacher block to the course and that part of it seems to work OK in that students can only see their own teachers to message them.  The student can send a message to the teacher.

Here's where it seems to go wrong:
- On the Dashboard of the teacher the Messages block says "No messages waiting". 
- On the Course page the Messages block says "Teacher not yet assigned to your group"
- When the teacher goes to messages to reply she cannot reply to the messages the student can see.

Cheers

Dave

**Comment by marxjohnson** [comment]
The block and the messaging system have had a re-write since this issue was raised. Please try again with the latest version (2.5) and open a new issue if the problem still occurs.
