### ISSUE TITLE
Error in Console

### ISSUE THREAD

**Issue by kimberwarden** [marxjohnson/moodle-block_messageteacher#21]
I have tried this on three different Moodle 3.0.6 servers, one of which was a brand new installation for the sole purpose of testing this issue...

When a student clicks the Message My Teacher link, an error appears in the browser's developer tools console that says "Uncaught TypeError: require is not a function"

If any kind of debugging is enabled, another error is generated when the user clicks the Send button: VM1470:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0 
The result is that the message form does not close or give a "Message Sent!" confirmation. This could be related to the fact that my Moodle installation does not currently send out e-mails, which is probably generating an error even though it does not display with debugging turned on.

**Comment by marxjohnson** [comment]
I am closing this issue because it is 2 years old and has no further activity. If your problem still occurs with the latest version (2.5), please open a new issue.
