### ISSUE TITLE
Bug in Appending Referring URL

### ISSUE THREAD

**Issue by andrewsolomon** [marxjohnson/moodle-block_messageteacher#22]
Hi Mark,

I'm running messageteacher 2.4 against Moodle 3.0.

When a student sends a message from within a quiz on a page like:

http://moodle.example.com/mod/quiz/attempt.php?attempt=47&page=9#q13

the email received by the teacher has the url appended as:

http://moodle.example.com/mod/quiz/attempt.php?attempt=47&amp;page=9

where the ampersand between the "attempt" and "page" parameters is escaped, and therefore when clicking it, only the first parameter takes effect (showing the whole quiz rather than the page the student was on).

Also (less important to me) the "#q13" anchor tag vanishes.

Andrew

p.s In spite of this bug, thanks for providing such an essential block!

**Comment by marxjohnson** [comment]
Hi, please try this again with version 2.5. It has had a major re-write including the appendurl functionality. If the problem still occurs, please open a new issue.
