### ISSUE TITLE
502 Bad Gateway on moodle 3.2

### ISSUE THREAD

**Issue by Andrewolico** [marxjohnson/moodle-block_messageteacher#23]
Hi Mark,

Using a custom theme on moodle 3.2 I'm getting a 502 Bad Gateway error.

Thanks

Andrew

**Comment by marxjohnson** [comment]
Hi Andrew,
Please can you give me a step-by-step guide to reproducing the error, including details about your server environment (OS, web server software etc)?
Thanks
Mark

**Comment by marxjohnson** [comment]
I am closing this issue because it is 2 years old and has no further activity. If your problem still occurs with the latest version (2.5), please open a new issue.
