### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by russofinn** [marxjohnson/moodle-block_messageteacher#24]
Error below

Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at webmaster@masteread.com.br to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by marxjohnson** [comment]
I am closing this issue because it is 2 years old and has no further activity. If your problem still occurs with the latest version (2.5), please open a new issue.
