### ISSUE TITLE
Message MyTeacher block error in Moodle 3.6

### ISSUE THREAD

**Issue by hftechsupport** [marxjohnson/moodle-block_messageteacher#28]
I updated Moodle to 3.6 version.  Now, when I press the "send" button to send a message through the Message My Teacher block the following error appears:

Exception - Argument 1 passed to message_send() must be an instance of core\message\message, instance of stdClass given, called in [dirroot]\blocks\messageteacher\message_form.php on line 89

Any suggestion?

**Comment by marxjohnson** [comment]
It sounds like there was a change to the core messaging API that requires an update to the way the block sends messages.  I will try and look at this in the near future.

**Comment by hftechsupport** [comment]
Thank you so much!

**Comment by el1c** [comment]
hi, did you find a solution?
thanks, 
e.c.

**Comment by hftechsupport** [comment]
Hi e.c.

The Message My Teacher block is still not working so instead I am using the Course Contacts block https://moodle.org/plugins/block_course_contacts

**Comment by el1c** [comment]
ok, thank you !!!

**Comment by marxjohnson** [comment]
This is now fixed in version 2.5.
