### ISSUE TITLE
Error in sending message

### ISSUE THREAD

**Issue by iramis** [marxjohnson/moodle-block_messageteacher#29]
Hi,
after the moodle upgrade, the block no longer works. 
Thanks

Moodle 3.6.2+ (Build: 20190201)

Debug info: 
Error code: messagefailed
Stack trace:
•	line 101 of /blocks/messageteacher/classes/message_form.php: block_messageteacher\message_failed_exception thrown
•	line 62 of /blocks/messageteacher/message.php: call to block_messageteacher\message_form->process()

**Comment by marxjohnson** [comment]
This is now fixed in version 2.5.
